[SystemSettings]
; Optimize Slate signed distance field text for performance
+CVars=UI.SlateSDFText.RasterizationMode=SdfApproximation
+CVars=UI.SlateSDFText.ResolutionLevel=1
; Reset Async Trace Hitch Threshold
+CVars=AsyncTraceDelegateHitchThresholdMS=0.75
; Forced by Unreal to non-scalable values
fx.Niagara.QualityLevel.Min=0
fx.Niagara.QualityLevel.Max=4

[/Script/Switch2RuntimeSettings.Switch2RuntimeSettings]
bSupportMobileRenderer=False
bSupportDesktopRenderer=True
bUseASTCTextures=False
bUseDistanceFields=True
TouchScreenUsage=None
bSupportFourFingerTap=False
JoyConDeadZone=0.200000
JoyConSensitivity=1.000000
ProControllerDeadZone=0.100000
ProControllerSensitivity=1.000000
VibrationAttenuationHF=1.000000
VibrationAttenuationLF=1.000000
InitialMaxControllers=2
InitialMinControllers=1
InitialEnableDualStickControllers=True
InitialEnableSingleStickControllers=True
InitialUseHorizontalSingleStick=True
InitialEnableSixAxisSensors=False
InitialUseRightJoyConForMotion=True
InitialEnableSingleMode=False
ProgramId=0x010091b022a8a000
ApplicationVersion=0
ApplicationVersionString=1.0.0
bUseBuildLabelAsGameNameInNonShippingBuilds=False
-SupportedLanguages=AmericanEnglish
+SupportedLanguages=AmericanEnglish
+SupportedLanguages=BritishEnglish
+SupportedLanguages=French
+SupportedLanguages=Italian
+SupportedLanguages=German
+SupportedLanguages=Spanish
+SupportedLanguages=Dutch
+SupportedLanguages=BrazilianPortuguese
+SupportedLanguages=LatinAmericanSpanish
+SupportedLanguages=SimplifiedChinese
+SupportedLanguages=TraditionalChinese
+SupportedLanguages=Korean
+SupportedLanguages=Japanese
+LocalizedTitles=(Language=AmericanEnglish,Title="PAW Patrol: Dino World",Publisher="Outright Games Ltd.")
+LocalizedTitles=(Language=BritishEnglish,Title="PAW Patrol: Dino World",Publisher="Outright Games Ltd.")
+LocalizedTitles=(Language=French,Title="PAW Patrol: Dino World",Publisher="Outright Games Ltd.")
+LocalizedTitles=(Language=Italian,Title="PAW Patrol: Dino World",Publisher="Outright Games Ltd.")
+LocalizedTitles=(Language=German,Title="PAW Patrol: Dino World",Publisher="Outright Games Ltd.")
+LocalizedTitles=(Language=Spanish,Title="PAW Patrol: Dino World",Publisher="Outright Games Ltd.")
+LocalizedTitles=(Language=Dutch,Title="PAW Patrol: Dino World",Publisher="Outright Games Ltd.")
+LocalizedTitles=(Language=BrazilianPortuguese,Title="PAW Patrol: Dino World",Publisher="Outright Games Ltd.")
+LocalizedTitles=(Language=LatinAmericanSpanish,Title="PAW Patrol: Dino World",Publisher="Outright Games Ltd.")
+LocalizedTitles=(Language=SimplifiedChinese,Title="PAW Patrol: Dino World",Publisher="Outright Games Ltd.")
+LocalizedTitles=(Language=TraditionalChinese,Title="PAW Patrol: Dino World",Publisher="Outright Games Ltd.")
+LocalizedTitles=(Language=Korean,Title="PAW Patrol: Dino World",Publisher="Outright Games Ltd.")
+LocalizedTitles=(Language=Japanese,Title="PAW Patrol: Dino World",Publisher="Outright Games Ltd.")
+AgeRatings=(Organization=ACB,Age=0)
+AgeRatings=(Organization=PEGI,Age=3)
+AgeRatings=(Organization=ClassInd,Age=10)
+AgeRatings=(Organization=IARCGeneric,Age=3)
+AgeRatings=(Organization=USK,Age=12)
+AgeRatings=(Organization=GRACGCRB,Age=0)
+AgeRatings=(Organization=ESRB,Age=10)
+AgeRatings=(Organization=OFLC,Age=0)
+AgeRatings=(Organization=PEGIBBFC,Age=3)
+AgeRatings=(Organization=PEGIPortugal,Age=3)
MainThreadStackSizeKB=64
DebugMainThreadStackSizeKB=128
SystemResourceSizeMB=20
SaveGameSizeKB=4096
SaveGameJournalSizeKB=1024
SaveGameSizeExpansionGranularityMB=8
bShowDataLossConfirmationDialog=True
bRouteGameUserSettingsToSaveGame=False
StartupAccountMode=Required
bStartupUserAccountIsOptional=False
bUserAccountSwitchLock=False
NintendoGameServersMode=None
ConserveBatteryLife=False
ApplicationErrorCode=BN6EA
bAllowScreenshots=True
bAllowVideoCapture=True
bAllowCrashReporting=False
bEnableCustomCrashHandling=False
bSuspendWhileInBackground=True
LogoType=LicensedByNintendo
bUseManualLogoHide=False
SystemHelpUrl=
BrowserCallbackUrl=
BrowserCallbackableUrl=
bBindBrowserToUser=False
bShowBrowserPointer=False
bGenerateSymbols=True

[ConsoleVariables]
pdw.SkipAllCutscenes=1

[Core.StringTable]
+StringTableRedirects=(StringTable="/Game/Data/StringText/ST_UI_Settings_Nebula.ST_UI_Settings_Nebula",OldKey="Game.Vibration",NewKey="Game.Vibration.Nintendo")
+StringTableRedirects=(StringTable="/Game/Data/StringText/ST_UserManagement_Nebula.ST_UserManagement_Nebula",OldKey="Text.ReconnectControllerP1",NewKey="Reconnect.ControllerP1.Switch")
+StringTableRedirects=(StringTable="/Game/Data/StringText/ST_UserManagement_Nebula.ST_UserManagement_Nebula",OldKey="Text.ReconnectControllerP2",NewKey="Reconnect.ControllerP1.Switch")
