;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
+GameplayTagTableList=/Game/Data/GameplayTags/DT_GameplayTag_InteractionBehaviour.DT_GameplayTag_InteractionBehaviour
+GameplayTagTableList=/Game/Data/GameplayTags/DT_GameplayTag_InteractionType.DT_GameplayTag_InteractionType
+GameplayTagTableList=/Game/Data/GameplayTags/DT_GameplayTag_Minigame.DT_GameplayTag_Minigame
+GameplayTagTableList=/Game/Data/GameplayTags/DT_GameplayTag_ID.DT_GameplayTag_ID
+GameplayTagTableList=/Game/Data/GameplayTags/DT_GameplayTag_Input.DT_GameplayTag_Input
+GameplayTagTableList=/Game/Data/GameplayTags/DT_GameplayTag_Collectible.DT_GameplayTag_Collectible
+GameplayTagTableList=/Game/Data/GameplayTags/DT_GameplayTag_PaleoCenter.DT_GameplayTag_PaleoCenter
+GameplayTagTableList=/Game/Data/GameplayTags/DT_GameplayTag_InteractionState.DT_GameplayTag_InteractionState
+GameplayTagTableList=/Game/Data/GameplayTags/Quest/DT_GameplayTag_Quest.DT_GameplayTag_Quest
+GameplayTagTableList=/Game/Data/GameplayTags/DT_GameplayTag_Facts.DT_GameplayTag_Facts
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Test.SkillType.TennisBall",NewTagName="Test.SkillType.Hit")
+GameplayTagRedirects=(OldTagName="InteractionType.Skill.Jump",NewTagName="InteractionType.Jump")
+GameplayTagRedirects=(OldTagName="Test.SkillType.Flying",NewTagName="InteractionType.Skill.Fly")
+GameplayTagRedirects=(OldTagName="Test.SkillType.Hit",NewTagName="InteractionType.Skill.Hit")
+GameplayTagRedirects=(OldTagName="Test.SkillType.Jump",NewTagName="InteractionType.Jump")
+GameplayTagRedirects=(OldTagName="Test.SkillType.Water",NewTagName="InteractionType.Skill.Water")
+GameplayTagRedirects=(OldTagName="Test.SkillType.Shake",NewTagName="InteractionType.Skill.Shake")
+GameplayTagRedirects=(OldTagName="Test.SkillType.Repair",NewTagName="InteractionType.Skill.Repair")
+GameplayTagRedirects=(OldTagName="Test.Interactions.Bounce",NewTagName="InteractionBehaviour.Bounce")
+GameplayTagRedirects=(OldTagName="Test.Interactions.Break",NewTagName="InteractionBehaviour.Break")
+GameplayTagRedirects=(OldTagName="Test.Interactions.Clean",NewTagName="InteractionBehaviour.Clean")
+GameplayTagRedirects=(OldTagName="Test.Interactions.Growth",NewTagName="InteractionBehaviour.Grow")
+GameplayTagRedirects=(OldTagName="Test.Interactions.Knockback",NewTagName="InteractionBehaviour.Knockback")
+GameplayTagRedirects=(OldTagName="Test.Interactions.Shake",NewTagName="InteractionBehaviour.Shake")
+GameplayTagRedirects=(OldTagName="Test.Interactions.Talk",NewTagName="InteractionBehaviour.Talk")
+GameplayTagRedirects=(OldTagName="Test.Interactions.Repair",NewTagName="InteractionBehaviour.Repair")
+GameplayTagRedirects=(OldTagName="Test.Interact.Action.Marshall",NewTagName="InteractionType.Base.Pup.Marshall")
+GameplayTagRedirects=(OldTagName="Test.Interact.Action.MarshallVehicle",NewTagName="InteractionType.Base.Vehicle.Marshall")
+GameplayTagRedirects=(OldTagName="Test.Interact.Action.Sky",NewTagName="InteractionType.Base.Pup.Skye")
+GameplayTagRedirects=(OldTagName="Test.Interact.Skill.Marshall",NewTagName="InteractionType.Base.Pup.Marshall")
+GameplayTagRedirects=(OldTagName="Test.Interact.Skill.Chase",NewTagName="InteractionType.Base.Pup.Chase")
+GameplayTagRedirects=(OldTagName="Test.Interact.SwapCharacter.Marshall",NewTagName="InteractionType.SwapCharacter.Pup.Marshall")
+GameplayTagRedirects=(OldTagName="Test.Interact.SwapCharacter.Skye",NewTagName="InteractionType.SwapCharacter.Pup.Skye")
+GameplayTagRedirects=(OldTagName="Test.Interact.Skill",NewTagName="InteractionType.Skill")
+GameplayTagRedirects=(OldTagName="FSM.Minigame.Succed",NewTagName="FSM.Minigame.Succeed")
+GameplayTagRedirects=(OldTagName="FSM.Minigame.State",NewTagName="FSM.Minigame.PlayState")
+GameplayTagRedirects=(OldTagName="Input.Action.Minigame.BottomButtomHold",NewTagName="Input.Action.Minigame.BottomButtonHold")
+GameplayTagRedirects=(OldTagName="FSM.MainMenu.ToGame",NewTagName="FSM.MainMenu.ContinueGame")
+GameplayTagList=(Tag="Back",DevComment="")
+GameplayTagList=(Tag="ComponentTag",DevComment="")
+GameplayTagList=(Tag="ComponentTag.BodyGroom",DevComment="")
+GameplayTagList=(Tag="ComponentTag.CharacterMesh",DevComment="")
+GameplayTagList=(Tag="ComponentTag.HatMesh",DevComment="")
+GameplayTagList=(Tag="ComponentTag.HeadGroom",DevComment="")
+GameplayTagList=(Tag="ComponentTag.Plane",DevComment="")
+GameplayTagList=(Tag="ComponentTag.SkillMesh",DevComment="")
+GameplayTagList=(Tag="ComponentTag.VehicleMesh",DevComment="")
+GameplayTagList=(Tag="ComponentTag.VheicleMesh",DevComment="")
+GameplayTagList=(Tag="Cutscene.01",DevComment="")
+GameplayTagList=(Tag="Cutscene.02",DevComment="")
+GameplayTagList=(Tag="Cutscene.03",DevComment="")
+GameplayTagList=(Tag="Dialogue.Ryder",DevComment="")
+GameplayTagList=(Tag="Event.AutoSwap.EnableRefresh",DevComment="")
+GameplayTagList=(Tag="Event.LeavingSwimmingArea",DevComment="")
+GameplayTagList=(Tag="Facts",DevComment="")
+GameplayTagList=(Tag="Facts.PauseMenuOpened",DevComment="")
+GameplayTagList=(Tag="Flow.Root",DevComment="")
+GameplayTagList=(Tag="FSM.Back",DevComment="")
+GameplayTagList=(Tag="FSM.Credits",DevComment="")
+GameplayTagList=(Tag="FSM.Customization",DevComment="")
+GameplayTagList=(Tag="FSM.Cutscene",DevComment="")
+GameplayTagList=(Tag="FSM.Dialogue",DevComment="")
+GameplayTagList=(Tag="FSM.DinoCustomization",DevComment="")
+GameplayTagList=(Tag="FSM.Gameplay",DevComment="")
+GameplayTagList=(Tag="FSM.InitGame",DevComment="")
+GameplayTagList=(Tag="FSM.Intro.AutosaveWarning",DevComment="")
+GameplayTagList=(Tag="FSM.Intro.Logo",DevComment="")
+GameplayTagList=(Tag="FSM.Intro.Photosensitivity",DevComment="")
+GameplayTagList=(Tag="FSM.Intro.StartState",DevComment="")
+GameplayTagList=(Tag="FSM.Intro.ToWelcomeScreen",DevComment="")
+GameplayTagList=(Tag="FSM.Intro.Videos",DevComment="")
+GameplayTagList=(Tag="FSM.LoadUser",DevComment="")
+GameplayTagList=(Tag="FSM.MainMenu",DevComment="")
+GameplayTagList=(Tag="FSM.MainMenu.ApplySettings",DevComment="")
+GameplayTagList=(Tag="FSM.MainMenu.ContinueGame",DevComment="")
+GameplayTagList=(Tag="FSM.MainMenu.Credits",DevComment="")
+GameplayTagList=(Tag="FSM.MainMenu.LoadGame",DevComment="")
+GameplayTagList=(Tag="FSM.MainMenu.LoadSlot",DevComment="")
+GameplayTagList=(Tag="FSM.MainMenu.MainMenu",DevComment="")
+GameplayTagList=(Tag="FSM.MainMenu.NewGame",DevComment="")
+GameplayTagList=(Tag="FSM.MainMenu.Quit",DevComment="")
+GameplayTagList=(Tag="FSM.MainMenu.Save",DevComment="")
+GameplayTagList=(Tag="FSM.MainMenu.Settings",DevComment="")
+GameplayTagList=(Tag="FSM.Minigame",DevComment="")
+GameplayTagList=(Tag="FSM.Minigame.Cancelled",DevComment="")
+GameplayTagList=(Tag="FSM.Minigame.Completed",DevComment="")
+GameplayTagList=(Tag="FSM.Minigame.PlayState",DevComment="")
+GameplayTagList=(Tag="FSM.Minigame.Setup",DevComment="")
+GameplayTagList=(Tag="FSM.Minigame.Succeed",DevComment="")
+GameplayTagList=(Tag="FSM.MissingTag",DevComment="")
+GameplayTagList=(Tag="FSM.Pages.Cutscene",DevComment="")
+GameplayTagList=(Tag="FSM.Pages.MainMenu",DevComment="")
+GameplayTagList=(Tag="FSM.Pages.Pause",DevComment="")
+GameplayTagList=(Tag="FSM.PauseGame",DevComment="")
+GameplayTagList=(Tag="FSM.Proceed",DevComment="")
+GameplayTagList=(Tag="FSM.QuestMessage",DevComment="")
+GameplayTagList=(Tag="FSM.ReplayMinigames",DevComment="")
+GameplayTagList=(Tag="FSM.Reward",DevComment="")
+GameplayTagList=(Tag="FSM.RyderMenu",DevComment="")
+GameplayTagList=(Tag="FSM.SkipCutscene",DevComment="")
+GameplayTagList=(Tag="FSM.Switcher",DevComment="")
+GameplayTagList=(Tag="FSM.Teleport",DevComment="")
+GameplayTagList=(Tag="FSM.WelcomeScreen.ApplySettings",DevComment="")
+GameplayTagList=(Tag="FSM.WelcomeScreen.LoadMenu",DevComment="")
+GameplayTagList=(Tag="FSM.WelcomeScreen.LoadPersistentUser",DevComment="")
+GameplayTagList=(Tag="FSM.WelcomeScreen.PostLoadUser",DevComment="")
+GameplayTagList=(Tag="FSM.WelcomeScreen.Welcome",DevComment="")
+GameplayTagList=(Tag="GAS.DisableSkills",DevComment="")
+GameplayTagList=(Tag="GAS.Skill",DevComment="")
+GameplayTagList=(Tag="GAS.SwappingCharacter",DevComment="")
+GameplayTagList=(Tag="GAS.WaterGun.Progress",DevComment="")
+GameplayTagList=(Tag="ID.Minigame.GrapplingHook.00",DevComment="")
+GameplayTagList=(Tag="ID.Minigame.GrapplingHook.01",DevComment="")
+GameplayTagList=(Tag="ID.Vibration.Hit",DevComment="")
+GameplayTagList=(Tag="ID.Vibration.Medium",DevComment="")
+GameplayTagList=(Tag="ID.Vibration.Soft",DevComment="")
+GameplayTagList=(Tag="ID.Vibration.Strong",DevComment="")
+GameplayTagList=(Tag="Input.Action.ChangeCharacter",DevComment="")
+GameplayTagList=(Tag="Input.Action.GameplayPause",DevComment="")
+GameplayTagList=(Tag="Input.Action.Interact",DevComment="")
+GameplayTagList=(Tag="Input.Action.Jump",DevComment="")
+GameplayTagList=(Tag="Input.Action.Look",DevComment="")
+GameplayTagList=(Tag="Input.Action.Minigame.BottomButton",DevComment="")
+GameplayTagList=(Tag="Input.Action.Minigame.BottomButtonHold",DevComment="")
+GameplayTagList=(Tag="Input.Action.Minigame.LeftButton",DevComment="")
+GameplayTagList=(Tag="Input.Action.Minigame.LeftButtonHold",DevComment="")
+GameplayTagList=(Tag="Input.Action.Minigame.Move",DevComment="")
+GameplayTagList=(Tag="Input.Action.Minigame.RightButton",DevComment="")
+GameplayTagList=(Tag="Input.Action.Minigame.Skip",DevComment="")
+GameplayTagList=(Tag="Input.Action.Minigame.StopMinigame",DevComment="")
+GameplayTagList=(Tag="Input.Action.Minigame.TopButton",DevComment="")
+GameplayTagList=(Tag="Input.Action.Move",DevComment="")
+GameplayTagList=(Tag="Input.Action.Pause",DevComment="")
+GameplayTagList=(Tag="Input.Action.Skill",DevComment="")
+GameplayTagList=(Tag="Input.Action.SwapVehicle",DevComment="")
+GameplayTagList=(Tag="Input.Action.UI.Back",DevComment="")
+GameplayTagList=(Tag="Input.Action.UI.Confirm",DevComment="")
+GameplayTagList=(Tag="Input.MappingContext.Default",DevComment="")
+GameplayTagList=(Tag="Input.MappingContext.Interaction",DevComment="")
+GameplayTagList=(Tag="Input.MappingContext.Minigame",DevComment="")
+GameplayTagList=(Tag="Input.MappingContext.UIDefault",DevComment="")
+GameplayTagList=(Tag="InteractionBehaviour.Reset",DevComment="")
+GameplayTagList=(Tag="InteractionState.Diving",DevComment="")
+GameplayTagList=(Tag="InteractionState.Reset",DevComment="")
+GameplayTagList=(Tag="InteractionState.Swimming",DevComment="")
+GameplayTagList=(Tag="InteractionType.Minigame.DinoDrop",DevComment="")
+GameplayTagList=(Tag="InteractionType.Skill.Swim",DevComment="")
+GameplayTagList=(Tag="Map.Cave",DevComment="")
+GameplayTagList=(Tag="Map.DinoPlains",DevComment="")
+GameplayTagList=(Tag="Map.DinoShores",DevComment="")
+GameplayTagList=(Tag="Map.Jungle",DevComment="")
+GameplayTagList=(Tag="Map.Volcano",DevComment="")
+GameplayTagList=(Tag="NPC",DevComment="")
+GameplayTagList=(Tag="NPC.BabyDino",DevComment="")
+GameplayTagList=(Tag="NPC.BabyDino.2",DevComment="")
+GameplayTagList=(Tag="NPC.BabyDino.3",DevComment="")
+GameplayTagList=(Tag="NPC.BabyDinoMinigame",DevComment="")
+GameplayTagList=(Tag="NPC.Ryder",DevComment="")
+GameplayTagList=(Tag="Player.Pawn",DevComment="")
+GameplayTagList=(Tag="Player.Vehicle",DevComment="")
+GameplayTagList=(Tag="Quest",DevComment="")
+GameplayTagList=(Tag="Quest.00",DevComment="")
+GameplayTagList=(Tag="Quest.01",DevComment="")
+GameplayTagList=(Tag="Quest.00.Interactions.BabyDino",DevComment="")
+GameplayTagList=(Tag="Quest.00.Interactions.Hook",DevComment="")
+GameplayTagList=(Tag="Quest.00.Interactions.Leaf",DevComment="")
+GameplayTagList=(Tag="Quest.00.Interactions.Rock",DevComment="")
+GameplayTagList=(Tag="Quest.00.Minigames.02",DevComment="")
+GameplayTagList=(Tag="Quest.00.Minigames.03",DevComment="")
+GameplayTagList=(Tag="Quest.00.Trigger.01",DevComment="")
+GameplayTagList=(Tag="Quest.00.Trigger.02",DevComment="")
+GameplayTagList=(Tag="Quest.00.Trigger.03",DevComment="")
+GameplayTagList=(Tag="Quest.00.Trigger.04",DevComment="")
+GameplayTagList=(Tag="Quest.00.Trigger.05",DevComment="")
+GameplayTagList=(Tag="Quest.00.Trigger.06",DevComment="")
+GameplayTagList=(Tag="Quest.00.Trigger.07",DevComment="")
+GameplayTagList=(Tag="Quest.00.Trigger.08",DevComment="")
+GameplayTagList=(Tag="Quest.24.VehicleLoad",DevComment="")
+GameplayTagList=(Tag="Quest.BreadcrumbsTest",DevComment="")
+GameplayTagList=(Tag="Quest.BreadcrumbsTest.Step0",DevComment="")
+GameplayTagList=(Tag="Quest.BreadcrumbsTest.Step1",DevComment="")
+GameplayTagList=(Tag="Quest.BreadcrumbsTest.Step2",DevComment="")
+GameplayTagList=(Tag="Quest.BreadcrumbsTest.Step3",DevComment="")
+GameplayTagList=(Tag="Quest.BreadcrumbsTest.Step4",DevComment="")
+GameplayTagList=(Tag="Quest.Giver",DevComment="")
+GameplayTagList=(Tag="Quest.Target",DevComment="")
+GameplayTagList=(Tag="Quest.Target.Paleo",DevComment="")
+GameplayTagList=(Tag="Socket.PupSeat",DevComment="")
+GameplayTagList=(Tag="Teleport.BulldozerScoop",DevComment="")
+GameplayTagList=(Tag="Teleport.RhubarbCall",DevComment="")
+GameplayTagList=(Tag="Teleport.Tutorial",DevComment="")
+GameplayTagList=(Tag="Teleport.VehicleClaws",DevComment="")
+GameplayTagList=(Tag="Test.Animation.AskingHelp",DevComment="")
+GameplayTagList=(Tag="Test.Animation.Celebrating",DevComment="")
+GameplayTagList=(Tag="Test.Animation.Stop",DevComment="")
+GameplayTagList=(Tag="Test.Animation.Talking",DevComment="")
+GameplayTagList=(Tag="Test.FSM.Back",DevComment="")
+GameplayTagList=(Tag="Test.FSM.Cinematic",DevComment="")
+GameplayTagList=(Tag="Test.FSM.Gameplay",DevComment="")
+GameplayTagList=(Tag="Test.FSM.Generic.Continue",DevComment="")
+GameplayTagList=(Tag="Test.FSM.Gym",DevComment="")
+GameplayTagList=(Tag="Test.FSM.MainMenu",DevComment="")
+GameplayTagList=(Tag="Test.FSM.Pause",DevComment="")
+GameplayTagList=(Tag="Test.Growth.Stages.1",DevComment="")
+GameplayTagList=(Tag="Test.Growth.Stages.2",DevComment="")
+GameplayTagList=(Tag="Test.Growth.Stages.3",DevComment="")
+GameplayTagList=(Tag="Test.Identity.Clean",DevComment="")
+GameplayTagList=(Tag="Test.Identity.Minigames",DevComment="")
+GameplayTagList=(Tag="Test.Identity.NPC",DevComment="")
+GameplayTagList=(Tag="Test.Identity.NPC.1",DevComment="")
+GameplayTagList=(Tag="Test.Identity.NPC.2",DevComment="")
+GameplayTagList=(Tag="Test.Identity.NPC.3",DevComment="")
+GameplayTagList=(Tag="Test.Identity.Plant",DevComment="")
+GameplayTagList=(Tag="Test.Interact.Action",DevComment="")
+GameplayTagList=(Tag="Test.Interact.InteractArea",DevComment="")
+GameplayTagList=(Tag="Test.InteractionComponent.Hide",DevComment="")
+GameplayTagList=(Tag="Test.Interactions.Minigame",DevComment="")
+GameplayTagList=(Tag="Test.Interactions.Minigame.Finish",DevComment="")
+GameplayTagList=(Tag="Test.Interactions.Minigame.Start",DevComment="")
+GameplayTagList=(Tag="Test.Quest.Events.QuestNoTarget",DevComment="")
+GameplayTagList=(Tag="Test.Quest.Events.QuestTarget",DevComment="")
+GameplayTagList=(Tag="Test.SkillType.Hook",DevComment="")
+GameplayTagList=(Tag="Test.SkillType.WaterCannon",DevComment="")

