#include "K2Node/K2Node_FSMState.h"

#include "BlueprintActionDatabaseRegistrar.h"
#include "BlueprintNodeSpawner.h"
#include "EdGraph/EdGraph.h"
#include "FSM/NebulaFlowBaseFSM.h"
#include "FSM/NebulaFlowBaseFSMState.h"
#include "FunctionLibraries/NebulaFlowK2NodeFunctionLibrary.h"
#include "K2Node/K2Node_FSMEntryPoint.h"
#include "GameplayTagContainer.h"
#include "K2Node_Knot.h"
#include "NebulaFlow_UncookedOnly.h"

#define LOCTEXT_NAMESPACE "K2Node_FSMState"

const FName UK2Node_FSMState::DefaultOutputPinName(TEXT("Label"));
const FName UK2Node_FSMState::FSMStateLabelPinName(TEXT("Label"));
const FName UK2Node_FSMState::FSMStateClassPinName(TEXT("FSM State"));
const FName UK2Node_FSMState::FSMStateParameterPinName(TEXT("Parameter"));
const FName UK2Node_FSMState::FSMDefaultPinTag(TEXT("FSM.MissingTag"));

/* Begin UObject interface */

void UK2Node_FSMState::PostEditChangeProperty(struct FPropertyChangedEvent& PropertyChangedEvent)
{
	Super::PostEditChangeProperty(PropertyChangedEvent);

	FName PropertyName = (PropertyChangedEvent.Property != nullptr) ? PropertyChangedEvent.Property->GetFName() : NAME_None;
	if (PropertyName == TEXT("PinNames"))
	{
		// Duplicates are not allowed
		const int32 AddedElementIndex = PropertyChangedEvent.GetArrayIndex(PropertyName.ToString());
		if (AddedElementIndex >= 0 && AddedElementIndex < PinNames.Num())
		{
			FString PinString = PinNames[AddedElementIndex].ToString();
			PinString.ReplaceInline(TEXT(" "), TEXT(""));
			PinNames[AddedElementIndex] = FName(*PinString);

			const int32 FoundedIndex = PinNames.Find(PinNames[AddedElementIndex]);
			const int32 FoundedLastIndex = PinNames.FindLast(PinNames[AddedElementIndex]);
			if (FoundedIndex != AddedElementIndex || FoundedLastIndex != AddedElementIndex)
			{
				UE_LOG(LogNebulaFlowK2Node, Log, TEXT("Pin %s already exist."), *(PinNames[AddedElementIndex].ToString()));
				PinNames[AddedElementIndex] = UNebulaFlowK2NodeFunctionLibrary::GetUniqueName(PinNames, DefaultOutputPinName);
			}
		}

		ReconstructNode();
		GetGraph()->NotifyGraphChanged();
	}
	else if (PropertyName == TEXT("LabelTag"))
	{
		UEdGraphPin* FSMStateLabelPin = FindPin(FSMStateLabelPinName, EGPD_Input);
		if (FSMStateLabelPin)
		{
			FSMStateLabelPin->DefaultValue = LabelTag.ToString();
			Label = LabelTag.GetTagName();
		}
	}
	else if (PropertyName == TEXT("PinTagsContainer"))
	{
		const int32 AddedElementIndex = PropertyChangedEvent.GetArrayIndex(PropertyName.ToString());
		if (AddedElementIndex >= 0 && AddedElementIndex < PinTagsContainer.Num())
		{
			FString PinString = PinTagsContainer[AddedElementIndex].ToString();
			PinString.ReplaceInline(TEXT(" "), TEXT(""));
			PinTagsContainer[AddedElementIndex] = FGameplayTag::RequestGameplayTag(FName(PinString), false);

			const int32 FoundedIndex = PinTagsContainer.Find(PinTagsContainer[AddedElementIndex]);
			const int32 FoundedLastIndex = PinTagsContainer.FindLast(PinTagsContainer[AddedElementIndex]);
			if (FoundedIndex != AddedElementIndex || FoundedLastIndex != AddedElementIndex)
			{
				UE_LOG(LogNebulaFlowK2Node, Log, TEXT("Pin %s already exist."), *(PinTagsContainer[AddedElementIndex].ToString()));
				PinTagsContainer[AddedElementIndex] = FGameplayTag::RequestGameplayTag(FSMDefaultPinTag, false);
			}
		}

		PinNames.Empty();
		for (FGameplayTag PinTag : PinTagsContainer)
		{
			PinNames.Add(PinTag.GetTagName());
		}

		ReconstructNode();
	}
}

void UK2Node_FSMState::PostEditUndo()
{
	Super::PostEditUndo();

	for (UEdGraphPin* Pin : Pins)
	{
		UpdateTransitions(Pin);
		UpdateInputPinsValue(Pin);
	}
}

/* End of UObject interface */

/* Begin UEdGraphNode Interface */

void UK2Node_FSMState::AllocateDefaultPins()
{
	Super::AllocateDefaultPins();
	ValidateLabel();
	// Creates input pin
	CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Exec, UEdGraphSchema_K2::PN_Execute);

	// Creates FSMStateLabelPin
	if (!FindPin(FSMStateLabelPinName, EGPD_Input))
	{
		UEdGraphPin* FSMStateLabelPin = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Name, FSMStateLabelPinName);
		if (FSMStateLabelPin)
		{
			GetDefault<UEdGraphSchema_K2>()->SetPinAutogeneratedDefaultValue(FSMStateLabelPin, Label.ToString());
			FSMStateLabelPin->bNotConnectable = true;
		}
	}
	// Creates FSMStateParameterPin
	if (!FindPin(FSMStateParameterPinName, EGPD_Input))
	{
		UEdGraphPin* FSMStateParameter = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Name, FSMStateParameterPinName);
		if (FSMStateParameter)
		{
			GetDefault<UEdGraphSchema_K2>()->SetPinAutogeneratedDefaultValue(FSMStateParameter, Parameter.ToString());
			FSMStateParameter->bNotConnectable = true;
		}
	}

	// Creates FSMStateClassPin
	if (!FindPin(FSMStateClassPinName, EGPD_Input))
	{
		UEdGraphPin* FSMStateClassPin = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Class, UNebulaFlowBaseFSMState::StaticClass(), FSMStateClassPinName);
		if (FSMStateClassPin)
		{
			FSMStateClassPin->bNotConnectable = true;
		}
	}

	PinNames.Empty();
	for (FGameplayTag PinTag : PinTagsContainer)
	{
		PinNames.Add(PinTag.GetTagName());
	}
	for (FName& PinName : PinNames)
	{
		// Label with Name_NONE is not allowed
		if (PinName == NAME_None)
		{
			PinName = UNebulaFlowK2NodeFunctionLibrary::GetUniqueName(PinNames, DefaultOutputPinName);
		}

		// Creates output pins
		if (!FindPin(PinName, EGPD_Output))
		{
			CreatePin(EGPD_Output, UEdGraphSchema_K2::PC_Exec, PinName);
		}
	}

	UNebulaFlowBaseFSM* FSMOwner = UNebulaFlowK2NodeFunctionLibrary::GetFSMOwner(this);
	if (FSMOwner)
	{
		FFSMStateDescriptor* StateDataDescriptor = FSMOwner->FSMStructureMap.Find(Label);
		if (StateDataDescriptor)
		{
			// Sort TransitionToStateMap
			UNebulaFlowK2NodeFunctionLibrary::SortFSMStructureMapAsOutputPinList(PinNames, StateDataDescriptor->TransitionToStateMap);
		}
	}
}

void UK2Node_FSMState::ReconstructNode()
{
	// Updates label and parameters with node's value
	UEdGraphPin* FSMStateLabelPin = FindPin(FSMStateLabelPinName, EGPD_Input);
	if (FSMStateLabelPin)
	{
		Label = FName(*FSMStateLabelPin->DefaultValue);
		LabelTag = FGameplayTag::RequestGameplayTag(FName(*FSMStateLabelPin->DefaultValue), false);
	}
	UEdGraphPin* FSMStateParameterPin = FindPin(FSMStateParameterPinName, EGPD_Input);
	if (FSMStateLabelPin)
	{
		Parameter = FName(*FSMStateParameterPin->DefaultValue);
	}

	Super::ReconstructNode();
}

void UK2Node_FSMState::PostPasteNode()
{
	Super::PostPasteNode();

	// Checks duplicate labels
	UEdGraphPin* FSMStateLabelPin = FindPin(FSMStateLabelPinName, EGPD_Input);
	if (FSMStateLabelPin)
	{
		TArray<FName> StateLabelArray = {};
		GetStateLabelsInGraph(StateLabelArray);
		if (StateLabelArray.Contains(FName(*FSMStateLabelPin->DefaultValue)))
		{
			UE_LOG(LogNebulaFlowK2Node, Log, TEXT("State with label %s already exist."), *FSMStateLabelPin->DefaultValue);
			const FName UniqueName = UNebulaFlowK2NodeFunctionLibrary::GetUniqueName(StateLabelArray, "Copied");
			FSMStateLabelPin->DefaultValue = UniqueName.ToString();
		}
	}
}

void UK2Node_FSMState::DestroyNode()
{
	// Removes label state from FSMStructureMap
	UNebulaFlowBaseFSM* FSMOwner = UNebulaFlowK2NodeFunctionLibrary::GetFSMOwner(this);
	if (FSMOwner && FSMOwner->FSMStructureMap.Contains(Label))
	{
		FSMOwner->FSMStructureMap.Remove(Label);
		FSMOwner->FSMStructureMap.Compact();
		FSMOwner->FSMStructureMap.Shrink();
	}

	Super::DestroyNode();
}

void UK2Node_FSMState::PinConnectionListChanged(UEdGraphPin* Pin)
{
	Super::PinConnectionListChanged(Pin);

	UpdateTransitions(Pin);
}

void UK2Node_FSMState::PinDefaultValueChanged(UEdGraphPin* Pin)
{
	Super::PinDefaultValueChanged(Pin);

	UpdateInputPinsValue(Pin);
}

FText UK2Node_FSMState::GetNodeTitle(ENodeTitleType::Type TitleType) const
{
	return LOCTEXT("NodeTitle", "FSM State");
}

FText UK2Node_FSMState::GetTooltipText() const
{
	return LOCTEXT("NodeTooltip", "Nebula FSM State");
}

FLinearColor UK2Node_FSMState::GetNodeTitleColor() const
{
	return FLinearColor(0.0f, 1.0f, 0.5f);
}

/* End UEdGraphNode Interface */

/* Begin UK2Node Interface */

void UK2Node_FSMState::GetMenuActions(FBlueprintActionDatabaseRegistrar& ActionRegistrar) const
{
	UClass* NodeClass = GetClass();
	if (NodeClass && ActionRegistrar.IsOpenForRegistration(NodeClass))
	{
		UBlueprintNodeSpawner* NodeSpawner = UBlueprintNodeSpawner::Create(GetClass());
		check(NodeSpawner != nullptr);
		ActionRegistrar.AddBlueprintAction(NodeClass, NodeSpawner);
	}
}

void UK2Node_FSMState::EarlyValidation(class FCompilerResultsLog& MessageLog) const
{
	Super::EarlyValidation(MessageLog);

	// Checks if FSMStateClass has not been assigned 
	const UEdGraphPin* FSMStatePin = FindPin(FSMStateClassPinName, EGPD_Input);
	for (UEdGraphPin* Pin : Pins)
	{
		if (Pin->LinkedTo.Num() > 0 && FSMStatePin && !FSMStatePin->DefaultObject)
		{
			MessageLog.Error(*LOCTEXT("MissingFSMState", "Missing FSM State @@").ToString(), this);
			break;
		}
	}
}

bool UK2Node_FSMState::ShouldShowNodeProperties() const
{
	return true;
}

FText UK2Node_FSMState::GetMenuCategory() const
{
	return LOCTEXT("NodeCategory", "Nebula Flow Plugin");
}

/* End UK2Node Interface */

/* Begin IK2Node_AddPinInterface Interface */

void UK2Node_FSMState::AddInputPin()
{
	Modify();
	const FName PinName = UNebulaFlowK2NodeFunctionLibrary::GetUniqueName(PinNames, DefaultOutputPinName);
	PinNames.Add(PinName);
	PinTagsContainer.Add(FGameplayTag::RequestGameplayTag(PinName, false));
	CreatePin(EGPD_Output, UEdGraphSchema_K2::PC_Exec, PinName);
}

/* End IK2Node_AddPinInterface Interface */

FName UK2Node_FSMState::GetLabel() const
{
	return Label;
}

void UK2Node_FSMState::GetStateLabelsInGraph(TArray<FName>& InLabelArray) const
{
	const UEdGraph* Graph = GetGraph();
	if (Graph)
	{
		for (UEdGraphNode* Node : Graph->Nodes)
		{
			UK2Node_FSMState* FSMState = Cast<UK2Node_FSMState>(Node);
			if (FSMState)
			{
				InLabelArray.Add(FSMState->GetLabel());
			}
		}
	}
}

void UK2Node_FSMState::UpdateTransitions(UEdGraphPin* Pin)
{
	UNebulaFlowBaseFSM* FSMOwner = UNebulaFlowK2NodeFunctionLibrary::GetFSMOwner(this);
	if (FSMOwner)
	{
		UEdGraphPin* FSMStateLabelPin = Pin->GetOwningNode()->FindPin(FSMStateLabelPinName, EGPD_Input);
		if (FSMStateLabelPin)
		{
			FName FSMStateLabel = FName(*FSMStateLabelPin->DefaultValue);

			// If edited pin is connected adds state data to FSMStructureMap, else removes transition
			if (Pin->LinkedTo.Num() > 0)
			{
				if (Pin->Direction == EGPD_Input && Pin->PinName == UEdGraphSchema_K2::PN_Execute)
				{
					if (!FSMOwner->FSMStructureMap.Contains(FSMStateLabel))
					{
						// Adds FSMStateLabel
						FSMOwner->FSMStructureMap.Add(FSMStateLabel);

						const UEdGraphPin* FSMStateClassPin = Pin->GetOwningNode()->FindPin(FSMStateClassPinName, EGPD_Input);
						if (FSMStateClassPin)
						{
							// Adds FSMStateClass
							FFSMStateDescriptor& StateDataDescriptor = FSMOwner->FSMStructureMap[FSMStateLabel];
							StateDataDescriptor.FSMStateClass = Cast<UClass>(FSMStateClassPin->DefaultObject);

							// Finds connected output pins and adds state transition to TransitionToStateMap
							for (FName& PinName : PinNames)
							{
								const UEdGraphPin* OutputPin = Pin->GetOwningNode()->FindPin(PinName, EGPD_Output);
								if (OutputPin && OutputPin->LinkedTo.Num() > 0)
								{
									const UK2Node_FSMState* NextFSMStateNode = Cast<UK2Node_FSMState>(OutputPin->LinkedTo[0]->GetOwningNode());
									if (NextFSMStateNode)
									{
										const UEdGraphPin* NextFSMStateLabelPin = NextFSMStateNode->FindPin(UK2Node_FSMState::FSMStateLabelPinName, EGPD_Input);
										if (NextFSMStateLabelPin)
										{
											const FName NextFSMStateLabel = FName(*NextFSMStateLabelPin->DefaultValue);
											if (!StateDataDescriptor.TransitionToStateMap.Contains(PinName))
											{
												StateDataDescriptor.TransitionToStateMap.Add(PinName, NextFSMStateLabel);
											}
											else
											{
												StateDataDescriptor.TransitionToStateMap[PinName] = NextFSMStateLabel;
											}
										}
									}
								}
							}

							// Adds FSMStateParameter
							const UEdGraphPin* FSMStateParameterPin = Pin->GetOwningNode()->FindPin(FSMStateParameterPinName, EGPD_Input);
							if (FSMStateParameterPin)
							{
								StateDataDescriptor.StateParameter = FName(*FSMStateParameterPin->DefaultValue);
							}
						}
					}

					// Reroute management
					// For each linked pin connected at the input pin
					for (UEdGraphPin* LinkedPin : Pin->LinkedTo)
					{
						// Until find a FSM node or the last unconnected knot
						UK2Node_Knot* KnotNode = Cast<UK2Node_Knot>(LinkedPin->GetOwningNode());
						while (KnotNode && KnotNode->Pins[0]->LinkedTo.Num() > 0)
						{
							// For each linked pin connected to current knot
							for (UEdGraphPin* LinkedToKnotPin : KnotNode->Pins[0]->LinkedTo)
							{
								if (UK2Node_FSMState* FSMOutputState = Cast<UK2Node_FSMState>(LinkedToKnotPin->GetOwningNode()))
								{
									const UEdGraphPin* OutputFSMStateLabelPin = FSMOutputState->FindPin(FSMStateLabelPinName, EGPD_Input);
									if (OutputFSMStateLabelPin)
									{
										// Finds FSMInputState in FSMStructureMap
										const FName OutputFSMStateLabel = FName(*OutputFSMStateLabelPin->DefaultValue);
										FFSMStateDescriptor* OutputStateDataDescriptor = FSMOwner->FSMStructureMap.Find(OutputFSMStateLabel);
										if (OutputStateDataDescriptor)
										{
											// For each output pin
											for (FName OutputPinName : FSMOutputState->PinNames)
											{
												// Finds output pin of FSMInputState connected to current knot
												const UEdGraphPin* OutputPin = FSMOutputState->FindPin(OutputPinName, EGPD_Output);
												if (OutputPin &&
													OutputPin->LinkedTo.Num() > 0 &&
													Cast<UK2Node_Knot>(OutputPin->LinkedTo[0]->GetOwningNode()) == KnotNode)
												{
													if (!OutputStateDataDescriptor->TransitionToStateMap.Contains(OutputPinName))
													{
														// Adds transition for input state to this output state
														OutputStateDataDescriptor->TransitionToStateMap.Add(OutputPinName, FSMStateLabel);
													}
													else
													{
														// Updates transition
														OutputStateDataDescriptor->TransitionToStateMap.Add(OutputPinName, FSMStateLabel);
													}
												}
											}
										}
									}
								}
								else if (UK2Node_FSMEntryPoint* FSMInputEntryPoint = Cast<UK2Node_FSMEntryPoint>(LinkedToKnotPin->GetOwningNode()))
								{
									// For each output pin
									for (FName OutputPinName : FSMInputEntryPoint->PinNames)
									{
										// Finds output pin of FSMInputEntryPoint connected to current knot
										const UEdGraphPin* OutputPin = FSMInputEntryPoint->FindPin(OutputPinName, EGPD_Output);
										if (OutputPin &&
											OutputPin->LinkedTo.Num() > 0 &&
											Cast<UK2Node_Knot>(OutputPin->LinkedTo[0]->GetOwningNode()) == KnotNode &&
											!FSMOwner->LabelToEntryPointMap.Contains(OutputPinName))
										{
											// Adds transition for input state to this output state
											FSMOwner->LabelToEntryPointMap.Add(OutputPinName, FSMStateLabel);

											// Updates default label
											FSMInputEntryPoint->UpdateDefaultLabel();
										}
									}
								}

								LinkedPin = LinkedToKnotPin;
							}
							KnotNode = Cast<UK2Node_Knot>(LinkedPin->GetOwningNode());
						}
					}
				}
				else if (Pin->Direction == EGPD_Output)
				{
					FFSMStateDescriptor* StateDataDescriptor = FSMOwner->FSMStructureMap.Find(FSMStateLabel);
					if (StateDataDescriptor)
					{
						// Adds or updates state transition to TransitionToStateMap
						const UK2Node_FSMState* NextFSMStateNode = Cast<UK2Node_FSMState>(Pin->LinkedTo[0]->GetOwningNode());
						if (NextFSMStateNode)
						{
							const UEdGraphPin* NextFSMStateLabelPin = NextFSMStateNode->FindPin(UK2Node_FSMState::FSMStateLabelPinName, EGPD_Input);
							if (NextFSMStateLabelPin)
							{
								const FName NextFSMStateLabel = FName(*NextFSMStateLabelPin->DefaultValue);
								if (!StateDataDescriptor->TransitionToStateMap.Contains(Pin->PinName))
								{
									StateDataDescriptor->TransitionToStateMap.Add(Pin->PinName, NextFSMStateLabel);
								}
								else
								{
									StateDataDescriptor->TransitionToStateMap[Pin->PinName] = NextFSMStateLabel;
								}
							}
						}
						else
						{
							UEdGraphPin* LinkedPin = Pin->LinkedTo[0];
							// Until find a FSM node or the last unconnected knot
							UK2Node_Knot* KnotNode = Cast<UK2Node_Knot>(LinkedPin->GetOwningNode());
							while (KnotNode && KnotNode->Pins[1]->LinkedTo.Num() > 0)
							{
								// For each linked pin connected to current knot
								for (UEdGraphPin* LinkedToKnotPin : KnotNode->Pins[1]->LinkedTo)
								{
									UK2Node_FSMState* FSMInputState = Cast<UK2Node_FSMState>(LinkedToKnotPin->GetOwningNode());
									if (FSMInputState)
									{
										const UEdGraphPin* InputFSMStateLabelPin = FSMInputState->FindPin(FSMStateLabelPinName, EGPD_Input);
										if (InputFSMStateLabelPin)
										{
											// Finds FSMInputState in FSMStructureMap
											const FName InputFSMStateLabel = FName(*InputFSMStateLabelPin->DefaultValue);
											if (!StateDataDescriptor->TransitionToStateMap.Contains(Pin->PinName))
											{
												// Adds transition for input state to this output state
												StateDataDescriptor->TransitionToStateMap.Add(Pin->PinName, InputFSMStateLabel);
											}
											else
											{
												// Updates transition
												StateDataDescriptor->TransitionToStateMap[Pin->PinName] = InputFSMStateLabel;
											}
										}
									}
									LinkedPin = LinkedToKnotPin;
								}
								KnotNode = Cast<UK2Node_Knot>(LinkedPin->GetOwningNode());
							}
						}

						// Sort TransitionToStateMap
						UNebulaFlowK2NodeFunctionLibrary::SortFSMStructureMapAsOutputPinList(PinNames, StateDataDescriptor->TransitionToStateMap);
					}
				}
			}
			else
			{
				if (Pin->Direction == EGPD_Input && Pin->PinName == UEdGraphSchema_K2::PN_Execute)
				{
					// Removes FSMState
					if (FSMOwner->FSMStructureMap.Contains(FSMStateLabel))
					{
						FSMOwner->FSMStructureMap.Remove(FSMStateLabel);
						FSMOwner->FSMStructureMap.Compact();
						FSMOwner->FSMStructureMap.Shrink();
					}
				}
				else if (Pin->Direction == EGPD_Output)
				{
					// Removes transition
					FFSMStateDescriptor* StateDataDescriptor = FSMOwner->FSMStructureMap.Find(FSMStateLabel);
					if (StateDataDescriptor && StateDataDescriptor->TransitionToStateMap.Contains(Pin->PinName))
					{
						StateDataDescriptor->TransitionToStateMap.Remove(Pin->PinName);
						StateDataDescriptor->TransitionToStateMap.Compact();
						StateDataDescriptor->TransitionToStateMap.Shrink();
					}
				}
			}
		}
	}
}

void UK2Node_FSMState::UpdateInputPinsValue(UEdGraphPin* Pin)
{
	if (Pin->Direction == EGPD_Input)
	{
		UNebulaFlowBaseFSM* FSMOwner = UNebulaFlowK2NodeFunctionLibrary::GetFSMOwner(this);
		if (FSMOwner)
		{
			UEdGraphPin* FSMStateLabelPin = Pin->GetOwningNode()->FindPin(FSMStateLabelPinName, EGPD_Input);
			if (FSMStateLabelPin)
			{
				const FName FSMStateLabel = FName(*FSMStateLabelPin->DefaultValue);

				if (Pin->PinName == FSMStateLabelPinName)
				{
					// Checks duplicate labels
					TArray<FName> StateLabelArray = {};
					GetStateLabelsInGraph(StateLabelArray);
					if (!StateLabelArray.Contains(FSMStateLabel))
					{
						const UEdGraphPin* InputPin = Pin->GetOwningNode()->FindPin(UEdGraphSchema_K2::PN_Execute, EGPD_Input);
						if (InputPin->LinkedTo.Num() > 0)
						{
							// Updates Entrypoint with new value
							for (auto& LabelToEntryPoint : FSMOwner->LabelToEntryPointMap)
							{
								if (LabelToEntryPoint.Value == Label)
								{
									LabelToEntryPoint.Value = FSMStateLabel;
								}
							}

							// Updates transitions
							for (auto& FSMStructure : FSMOwner->FSMStructureMap)
							{
								for (auto& TransitionToState : FSMStructure.Value.TransitionToStateMap)
								{
									if (TransitionToState.Value == Label)
									{
										TransitionToState.Value = FSMStateLabel;
									}
								}
							}
						}

						// Updates state name
						if (FSMOwner->FSMStructureMap.Contains(Label))
						{
							const FFSMStateDescriptor StateDataDescriptor = FSMOwner->FSMStructureMap[Label];
							FSMOwner->FSMStructureMap.Remove(Label);
							FSMOwner->FSMStructureMap.Compact();
							FSMOwner->FSMStructureMap.Shrink();
							FSMOwner->FSMStructureMap.Emplace(FSMStateLabel, StateDataDescriptor);
						}

						// Updates label
						Label = FSMStateLabel;
					}
					else
					{
						UE_LOG(LogNebulaFlowK2Node, Log, TEXT("State with label %s already exist."), *FSMStateLabelPin->DefaultValue);
						FSMStateLabelPin->DefaultValue = Label.ToString();
					}
				}
				else if (Pin->PinName == FSMStateClassPinName)
				{
					// Updates FSMStateClass 
					FFSMStateDescriptor* StateDataDescriptor = FSMOwner->FSMStructureMap.Find(FSMStateLabel);
					if (StateDataDescriptor)
					{
						const UEdGraphPin* FSMStatePin = Pin->GetOwningNode()->FindPin(FSMStateClassPinName, EGPD_Input);
						if (FSMStatePin)
						{
							StateDataDescriptor->FSMStateClass = Cast<UClass>(FSMStatePin->DefaultObject);
						}
					}
				}
				else if (Pin->PinName == FSMStateParameterPinName)
				{
					// Updates state parameter
					FFSMStateDescriptor* StateDataDescriptor = FSMOwner->FSMStructureMap.Find(FSMStateLabel);
					if (StateDataDescriptor)
					{
						const UEdGraphPin* FSMStateParameterPin = Pin->GetOwningNode()->FindPin(FSMStateParameterPinName, EGPD_Input);
						if (FSMStateParameterPin)
						{
							StateDataDescriptor->StateParameter = FName(*FSMStateParameterPin->DefaultValue);
						}
					}
				}
			}
		}
	}
}

void UK2Node_FSMState::ValidateLabel()
{

	UEdGraph* Graph = GetGraph();
	TArray<UK2Node_FSMState*> StateNodes;
	Graph->GetNodesOfClass(StateNodes);
	bool bValid = true;
	for (const auto* StateNode : StateNodes)
	{
		if (StateNode != this && Label == StateNode->Label)
		{
			bValid = false;
			break;
		}
	}
	if (bValid)
	{
		return;
	}
	FName OldLabel = Label;
	int32 Index = 0;
	while (!bValid)
	{
		bValid = true;
		FName TempLabel = *(OldLabel.ToString() + "_" + FString::FromInt(Index));
		for (const auto* StateNode : StateNodes)
		{
			if (StateNode != this && TempLabel == StateNode->Label)
			{
				bValid = false;
				break;
			}
		}
		if (bValid)
		{
			Label = TempLabel;
		}
		Index++;
	}
	UEdGraphPin* FSMStateLabelPin = FindPin(FSMStateLabelPinName, EGPD_Input);
	if (FSMStateLabelPin)
	{
		Label = FName(*FSMStateLabelPin->DefaultValue);
	}
}

#undef LOCTEXT_NAMESPACE
