[Switch DeviceProfile]
DeviceType=Switch
BaseProfileName=

;TextureGroup
;TEXTUREGROUP_Project01 = Building
;TEXTUREGROUP_Project02 = BuildingNormalMap
;TEXTUREGROUP_Project03 = BuildingSpecular
;TEXTUREGROUP_Project04 = Prop
;TEXTUREGROUP_Project05 = PropNormalMap
;TEXTUREGROUP_Project06 = PropSpecular
;TEXTUREGROUP_Project07 = AtlasCharacter
;TEXTUREGROUP_Project08 = AtlasCharacterNormalMap
;TEXTUREGROUP_Project09 = AtlasCharacterSpecular
;TEXTUREGROUP_Project10 = AtlasWeapon
;TEXTUREGROUP_Project11 = AtlasWeaponNormalMap
;TEXTUREGROUP_Project12 = AtlasWeaponSpecular
;TEXTUREGROUP_Project13 = AtlasVehicle
;TEXTUREGROUP_Project14 = AtlasVehicleNormalMap
;TEXTUREGROUP_Project15 = AtlasVehicleSpecular
;TEXTUREGROUP_Project16 = AtlasBuilding
;TEXTUREGROUP_Project17 = AtlasBuildingNormalMap
;TEXTUREGROUP_Project18 = AtlasBuildingSpecular
;TEXTUREGROUP_Project19 = AtlasProp
;TEXTUREGROUP_Project20 = AtlasPropNormalMap
;TEXTUREGROUP_Project21 = AtlasPropSpecular
+TextureLODGroups=(Group=TEXTUREGROUP_World,				MinLODSize=1, MaxLODSize=4096,	LODBias=1, MinMagFilter=aniso,	MipFilter=point,	MipGenSettings=TMGS_SimpleAverage						)
+TextureLODGroups=(Group=TEXTUREGROUP_WorldNormalMap,		MinLODSize=1, MaxLODSize=4096,	LODBias=1, MinMagFilter=aniso,	MipFilter=point,	MipGenSettings=TMGS_SimpleAverage						)
+TextureLODGroups=(Group=TEXTUREGROUP_WorldSpecular,		MinLODSize=1, MaxLODSize=4096,	LODBias=1, MinMagFilter=aniso,	MipFilter=point,	MipGenSettings=TMGS_SimpleAverage						)
+TextureLODGroups=(Group=TEXTUREGROUP_Character,			MinLODSize=1, MaxLODSize=4096,	LODBias=1, MinMagFilter=aniso,	MipFilter=point,	MipGenSettings=TMGS_SimpleAverage						)
+TextureLODGroups=(Group=TEXTUREGROUP_CharacterNormalMap,	MinLODSize=1, MaxLODSize=4096,	LODBias=1, MinMagFilter=aniso,	MipFilter=point,	MipGenSettings=TMGS_SimpleAverage						)
+TextureLODGroups=(Group=TEXTUREGROUP_CharacterSpecular,	MinLODSize=1, MaxLODSize=4096,	LODBias=1, MinMagFilter=aniso,	MipFilter=point,	MipGenSettings=TMGS_SimpleAverage						)
+TextureLODGroups=(Group=TEXTUREGROUP_Weapon,				MinLODSize=1, MaxLODSize=4096,	LODBias=1, MinMagFilter=aniso,	MipFilter=point,	MipGenSettings=TMGS_SimpleAverage						)
+TextureLODGroups=(Group=TEXTUREGROUP_WeaponNormalMap,		MinLODSize=1, MaxLODSize=4096,	LODBias=1, MinMagFilter=aniso,	MipFilter=point,	MipGenSettings=TMGS_SimpleAverage						)
+TextureLODGroups=(Group=TEXTUREGROUP_WeaponSpecular,		MinLODSize=1, MaxLODSize=4096,	LODBias=1, MinMagFilter=aniso,	MipFilter=point,	MipGenSettings=TMGS_SimpleAverage						)
+TextureLODGroups=(Group=TEXTUREGROUP_Vehicle,				MinLODSize=1, MaxLODSize=4096,	LODBias=1, MinMagFilter=aniso,	MipFilter=point,	MipGenSettings=TMGS_SimpleAverage						)
+TextureLODGroups=(Group=TEXTUREGROUP_VehicleNormalMap,		MinLODSize=1, MaxLODSize=4096,	LODBias=1, MinMagFilter=aniso,	MipFilter=point,	MipGenSettings=TMGS_SimpleAverage						)
+TextureLODGroups=(Group=TEXTUREGROUP_VehicleSpecular,		MinLODSize=1, MaxLODSize=4096,	LODBias=1, MinMagFilter=aniso,	MipFilter=point,	MipGenSettings=TMGS_SimpleAverage						)
+TextureLODGroups=(Group=TEXTUREGROUP_Effects,				MinLODSize=1, MaxLODSize=4096,	LODBias=1, MinMagFilter=linear,	MipFilter=point,	MipGenSettings=TMGS_SimpleAverage						)
+TextureLODGroups=(Group=TEXTUREGROUP_Skybox,				MinLODSize=1, MaxLODSize=4096,	LODBias=1, MinMagFilter=aniso,	MipFilter=point,	MipGenSettings=TMGS_SimpleAverage						)
+TextureLODGroups=(Group=TEXTUREGROUP_UI,					MinLODSize=1, MaxLODSize=4096,	LODBias=1, MinMagFilter=aniso,	MipFilter=point,	MipGenSettings=TMGS_SimpleAverage, NumStreamedMips= 1	)
+TextureLODGroups=(Group=TEXTUREGROUP_RenderTarget,			MinLODSize=1, MaxLODSize=512,	LODBias=0, MinMagFilter=aniso,	MipFilter=point,	MipGenSettings=TMGS_SimpleAverage						)
+TextureLODGroups=(Group=TEXTUREGROUP_Terrain_Heightmap,	MinLODSize=1, MaxLODSize=8192,	LODBias=0, MinMagFilter=aniso,	MipFilter=point,	MipGenSettings=TMGS_SimpleAverage						)
+TextureLODGroups=(Group=TEXTUREGROUP_Terrain_Weightmap,	MinLODSize=1, MaxLODSize=8192,	LODBias=0, MinMagFilter=aniso,	MipFilter=point,	MipGenSettings=TMGS_SimpleAverage						)
+TextureLODGroups=(Group=TEXTUREGROUP_HierarchicalLOD,		MinLODSize=1, MaxLODSize=4096,	LODBias=0, MinMagFilter=aniso,	MipFilter=point,	MipGenSettings=TMGS_SimpleAverage, NumStreamedMips=-1	)
+TextureLODGroups=(Group=TEXTUREGROUP_IESLightProfile,		MinLODSize=1, MaxLODSize=2048,	LODBias=0, MinMagFilter=aniso,	MipFilter=point,	MipGenSettings=TMGS_SimpleAverage, NumStreamedMips=-1	)
+TextureLODGroups=(Group=TEXTUREGROUP_16BitData,											LODBias=0, MinMagFilter=point,	MipFilter=point,	MipGenSettings=TMGS_NoMipmaps							)
+TextureLODGroups=(Group=TEXTUREGROUP_Project01,			MinLODSize=1, MaxLODSize=4096,  LODBias=1, MinMagFilter=aniso,	MipFilter=point,	MipGenSettings=TMGS_SimpleAverage, NumStreamedMips=-1	)
+TextureLODGroups=(Group=TEXTUREGROUP_Project02,			MinLODSize=1, MaxLODSize=4096,	LODBias=1, MinMagFilter=aniso,	MipFilter=point,	MipGenSettings=TMGS_SimpleAverage, NumStreamedMips=-1	)
+TextureLODGroups=(Group=TEXTUREGROUP_Project03,			MinLODSize=1, MaxLODSize=4096,	LODBias=1, MinMagFilter=aniso,	MipFilter=point,	MipGenSettings=TMGS_SimpleAverage, NumStreamedMips=-1	)
+TextureLODGroups=(Group=TEXTUREGROUP_Project04,			MinLODSize=1, MaxLODSize=4096,	LODBias=1, MinMagFilter=aniso,	MipFilter=point,	MipGenSettings=TMGS_SimpleAverage, NumStreamedMips=-1	)
+TextureLODGroups=(Group=TEXTUREGROUP_Project05,			MinLODSize=1, MaxLODSize=4096,	LODBias=1, MinMagFilter=aniso,	MipFilter=point,	MipGenSettings=TMGS_SimpleAverage, NumStreamedMips=-1	)
+TextureLODGroups=(Group=TEXTUREGROUP_Project06,			MinLODSize=1, MaxLODSize=4096,	LODBias=1, MinMagFilter=aniso,	MipFilter=point,	MipGenSettings=TMGS_SimpleAverage, NumStreamedMips=-1	)
+TextureLODGroups=(Group=TEXTUREGROUP_Project07,			MinLODSize=1, MaxLODSize=4096,	LODBias=1, MinMagFilter=aniso,	MipFilter=point,	MipGenSettings=TMGS_SimpleAverage, NumStreamedMips=-1	)
+TextureLODGroups=(Group=TEXTUREGROUP_Project08,			MinLODSize=1, MaxLODSize=4096,	LODBias=1, MinMagFilter=aniso,	MipFilter=point,	MipGenSettings=TMGS_SimpleAverage, NumStreamedMips=-1	)
+TextureLODGroups=(Group=TEXTUREGROUP_Project09,			MinLODSize=1, MaxLODSize=4096,	LODBias=1, MinMagFilter=aniso,	MipFilter=point,	MipGenSettings=TMGS_SimpleAverage, NumStreamedMips=-1	)
+TextureLODGroups=(Group=TEXTUREGROUP_Project10,			MinLODSize=1, MaxLODSize=4096,	LODBias=1, MinMagFilter=aniso,	MipFilter=point,	MipGenSettings=TMGS_SimpleAverage, NumStreamedMips=-1	)
+TextureLODGroups=(Group=TEXTUREGROUP_Project11,			MinLODSize=1, MaxLODSize=4096,	LODBias=1, MinMagFilter=aniso,	MipFilter=point,	MipGenSettings=TMGS_SimpleAverage, NumStreamedMips=-1	)
+TextureLODGroups=(Group=TEXTUREGROUP_Project12,			MinLODSize=1, MaxLODSize=4096,	LODBias=1, MinMagFilter=aniso,	MipFilter=point,	MipGenSettings=TMGS_SimpleAverage, NumStreamedMips=-1	)
+TextureLODGroups=(Group=TEXTUREGROUP_Project13,			MinLODSize=1, MaxLODSize=4096,	LODBias=1, MinMagFilter=aniso,	MipFilter=point,	MipGenSettings=TMGS_SimpleAverage, NumStreamedMips=-1	)
+TextureLODGroups=(Group=TEXTUREGROUP_Project14,			MinLODSize=1, MaxLODSize=4096,	LODBias=1, MinMagFilter=aniso,	MipFilter=point,	MipGenSettings=TMGS_SimpleAverage, NumStreamedMips=-1	)
+TextureLODGroups=(Group=TEXTUREGROUP_Project15,			MinLODSize=1, MaxLODSize=4096,	LODBias=1, MinMagFilter=aniso,	MipFilter=point,	MipGenSettings=TMGS_SimpleAverage, NumStreamedMips=-1	)
+TextureLODGroups=(Group=TEXTUREGROUP_Project16,			MinLODSize=1, MaxLODSize=4096,	LODBias=1, MinMagFilter=aniso,	MipFilter=point,	MipGenSettings=TMGS_SimpleAverage, NumStreamedMips=-1	)
+TextureLODGroups=(Group=TEXTUREGROUP_Project17,			MinLODSize=1, MaxLODSize=4096,	LODBias=1, MinMagFilter=aniso,	MipFilter=point,	MipGenSettings=TMGS_SimpleAverage, NumStreamedMips=-1	)
+TextureLODGroups=(Group=TEXTUREGROUP_Project18,			MinLODSize=1, MaxLODSize=4096,	LODBias=1, MinMagFilter=aniso,	MipFilter=point,	MipGenSettings=TMGS_SimpleAverage, NumStreamedMips=-1	)
+TextureLODGroups=(Group=TEXTUREGROUP_Project19,			MinLODSize=1, MaxLODSize=4096,	LODBias=1, MinMagFilter=aniso,	MipFilter=point,	MipGenSettings=TMGS_SimpleAverage, NumStreamedMips=-1	)
+TextureLODGroups=(Group=TEXTUREGROUP_Project20,			MinLODSize=1, MaxLODSize=4096,	LODBias=1, MinMagFilter=aniso,	MipFilter=point,	MipGenSettings=TMGS_SimpleAverage, NumStreamedMips=-1	)
+TextureLODGroups=(Group=TEXTUREGROUP_Project21,			MinLODSize=1, MaxLODSize=4096,	LODBias=1, MinMagFilter=aniso,	MipFilter=point,	MipGenSettings=TMGS_SimpleAverage, NumStreamedMips=-1	)
	
; Clear BaseSwitchDeviceProfile Rendering Settings
!CVars=ClearArray

; Rendering Settings

; Frame
+CVars=r.DynamicRes.OperationMode=2
+CVars=r.DynamicRes.FrameTimeBudget=33.33
+CVars=r.DynamicRes.MaxScreenPercentage=100
+CVars=rhi.SyncSlackMS=20
+CVars=rhi.syncinterval=2
+CVars=t.MaxFPS=30.0

; AntiAliasing
+CVars=r.AntiAliasingMethod=2											; TAA
+CVars=r.TemporalAA.Upsampling=0
+CVars=r.TemporalAASamples=4
+CVars=r.TemporalAACatmullRom=0

; Shadows
+CVars=r.Shadow.Denoiser=0
+CVars=r.Shadow.Preshadows=0
+CVars=r.DistanceFields=0
+CVars=r.AllowPointLightCubemapShadows=0
+CVars=r.SkyAtmosphere=0
+CVars=r.SkylightIntensityMultiplier=1
+CVars=r.LocalFogVolume=0
+CVars=r.VolumetricCloud=0

; HLOD
+CVars=r.HLOD.ForceDisableCastDynamicShadow=1

; Grass
+CVars=grass.MaxAsyncTasks=2

[SwitchConsole DeviceProfile]
DeviceType=Switch
BaseProfileName=Switch

; Clear BaseSwitchDeviceProfile Rendering Settings
!CVars=ClearArray

; Rendering Settings

; Scalability
+CVars=sg.AntiAliasingQuality=2
+CVars=sg.ViewDistanceQuality=0
+CVars=sg.ShadowQuality=0
+CVars=sg.GlobalIlluminationQuality=0
+CVars=sg.ReflectionQuality=0
+CVars=sg.PostProcessQuality=0
+CVars=sg.TextureQuality=2
+CVars=sg.EffectsQuality=0
+CVars=sg.FoliageQuality=0
+CVars=sg.ShadingQuality=0

; Frame
+CVars=r.SecondaryScreenPercentage.GameViewport=70						; 756p
+CVars=r.DynamicRes.MinScreenPercentage=80

[SwitchHandheld DeviceProfile]
DeviceType=Switch
BaseProfileName=Switch

; Clear BaseSwitchDeviceProfile Rendering Settings
!CVars=ClearArray

; Rendering Settings

; Scalability
+CVars=sg.AntiAliasingQuality=2
+CVars=sg.ViewDistanceQuality=0
+CVars=sg.ShadowQuality=0
+CVars=sg.GlobalIlluminationQuality=0
+CVars=sg.ReflectionQuality=0
+CVars=sg.PostProcessQuality=0
+CVars=sg.TextureQuality=2
+CVars=sg.EffectsQuality=0
+CVars=sg.FoliageQuality=0
+CVars=sg.ShadingQuality=0

; Frame
+CVars=r.DynamicRes.MinScreenPercentage=80
+CVars=r.SecondaryScreenPercentage.GameViewport=75						; 540p

; Foliage
+CVars=foliage.MaxEndCullDistance=12500
+CVars=foliage.DensityScale=0.1

[Cutscene Switch]
r.Streaming.Boost=1
grass.TickInterval=5

[Customization Switch]
r.Streaming.Boost=1

[Teleport Switch]
grass.TickInterval=5

[SplitScreen Switch]
r.Shadow.CSMCaching=0