[SystemSettings]
; Optimize Slate signed distance field text for performance
+CVars=UI.SlateSDFText.RasterizationMode=SdfApproximation
+CVars=UI.SlateSDFText.ResolutionLevel=1
; Reset Async Trace Hitch Threshold
+CVars=AsyncTraceDelegateHitchThresholdMS=0.75
; Forced by Unreal to non-scalable values
; https://udn.unrealengine.com/s/question/0D5QP00000BXjs20AD/why-is-fxniagaraqualitylevelmin-and-max-set-to-3-by-default-for-ps5
fx.Niagara.QualityLevel.Min=0
fx.Niagara.QualityLevel.Max=4

[OnlineSubsystemSwitch]
bEnabled=False

[/Script/SwitchRuntimeSettings.SwitchRuntimeSettings]
bSupportMobileRenderer=False
bSupportDesktopRenderer=True
ShadingMode=Deferred
bUseASTCTextures=False
bASTCUseRDO=False
bUseDistanceFields=True
TouchScreenUsage=None
bSupportFourFingerTap=False
JoyConDeadZone=0.200000
JoyConSensitivity=1.000000
ProControllerDeadZone=0.100000
ProControllerSensitivity=1.000000
VibrationAttenuationHF=1.000000
VibrationAttenuationLF=1.000000
InitialMaxControllers=1
InitialMinControllers=1
InitialEnableDualStickControllers=True
InitialEnableSingleStickControllers=True
InitialUseHorizontalSingleStick=True
InitialEnableSixAxisSensors=False
InitialUseRightJoyConForMotion=True
InitialZeroPointDriftMode=0
InitialEnableSingleMode=False
ProgramId=0x010091b022a8a000
ApplicationNameString=
ApplicationVersion=0
ApplicationVersionString=1.0.0
OriginalReleaseNSPPath=
bUseBuildLabelAsGameNameInNonShippingBuilds=False
-SupportedLanguages=AmericanEnglish
+SupportedLanguages=AmericanEnglish
+SupportedLanguages=BritishEnglish
+SupportedLanguages=French
+SupportedLanguages=Italian
+SupportedLanguages=German
+SupportedLanguages=Spanish
+SupportedLanguages=Dutch
+SupportedLanguages=BrazilianPortuguese
+SupportedLanguages=LatinAmericanSpanish
+SupportedLanguages=SimplifiedChinese
+SupportedLanguages=TraditionalChinese
+SupportedLanguages=Korean
+SupportedLanguages=Japanese
+LocalizedTitles=(Language=AmericanEnglish,Title="PAW Patrol™: Dino World",Publisher="Outright Games Ltd.")
+LocalizedTitles=(Language=BritishEnglish,Title="PAW Patrol™: Dino World",Publisher="Outright Games Ltd.")
+LocalizedTitles=(Language=French,Title="PAW Patrol™: Dino World",Publisher="Outright Games Ltd.")
+LocalizedTitles=(Language=Italian,Title="PAW Patrol™: Dino World",Publisher="Outright Games Ltd.")
+LocalizedTitles=(Language=German,Title="PAW Patrol™: Dino World",Publisher="Outright Games Ltd.")
+LocalizedTitles=(Language=Spanish,Title="PAW Patrol™: Dino World",Publisher="Outright Games Ltd.")
+LocalizedTitles=(Language=Dutch,Title="PAW Patrol™: Dino World",Publisher="Outright Games Ltd.")
+LocalizedTitles=(Language=BrazilianPortuguese,Title="PAW Patrol™: Dino World",Publisher="Outright Games Ltd.")
+LocalizedTitles=(Language=LatinAmericanSpanish,Title="PAW Patrol™: Dino World",Publisher="Outright Games Ltd.")
+LocalizedTitles=(Language=SimplifiedChinese,Title="PAW Patrol™: Dino World",Publisher="Outright Games Ltd.")
+LocalizedTitles=(Language=TraditionalChinese,Title="PAW Patrol™: Dino World",Publisher="Outright Games Ltd.")
+LocalizedTitles=(Language=Korean,Title="PAW Patrol™: Dino World",Publisher="Outright Games Ltd.")
+LocalizedTitles=(Language=Japanese,Title="PAW Patrol™: Dino World",Publisher="Outright Games Ltd.")
+AgeRatings=(Organization=ACB,Age=0)
+AgeRatings=(Organization=PEGI,Age=3)
+AgeRatings=(Organization=ClassInd,Age=10)
+AgeRatings=(Organization=IARCGeneric,Age=3)
+AgeRatings=(Organization=USK,Age=12)
+AgeRatings=(Organization=GRACGCRB,Age=0)
+AgeRatings=(Organization=ESRB,Age=10)
+AgeRatings=(Organization=OFLC,Age=0)
+AgeRatings=(Organization=PEGIBBFC,Age=3)
+AgeRatings=(Organization=PEGIPortugal,Age=3)
bGenerateSymbols=True
MainThreadStackSizeKB=64
DebugMainThreadStackSizeKB=80
SystemResourceSizeMB=32
SaveGameSizeKB=4096
SaveGameJournalSizeKB=2048
SaveGameSizeMaxMB=0
SaveGameJournalSizeMaxMB=0
SaveGameSizeExpansionGranularityMB=8
SaveGameOwnerId=
bShowDataLossConfirmationDialog=True
bRouteGameUserSettingsToSaveGame=False
TempDataSizeKB=0
CacheDataSizeKB=0
CacheDataJournalSizeKB=0
CacheStorageIndexMaxHexValueCorrected=0
CacheStorageDataAndJournalSizeMaxKB=0
GlobalFileCacheSizeKB=0
StartupAccountMode=Required
bStartupUserAccountIsOptional=False
bUserAccountSwitchLock=False
LocalCommunicationId=
LdnPassphrase=
FriendPresenceGroupId=
GameServerId=
GameServerAccessKey=
bEnableNEXLibrary=False
NintendoGameServersMode=None
ConserveBatteryLife=False
ApplicationErrorCode=BN6EA
bAllowScreenshots=True
bAllowVideoCapture=True
bAllowCrashReporting=False
bAllowScreenshotsWithCrashReports=False
bAllowScreenshotsWithCrashReportsInDevelopment=False
bEnableCustomCrashHandling=False
bSuspendWhileInBackground=True
bDemoBuild=False
bAllowAOCInstallWhileRunning=False
bDisableCPUBoostDuringLoad=False
bHasInGameVoiceChat=False
LogoType=LicensedByNintendo
bUseManualLogoHide=False
SystemHelpUrl=
BrowserCallbackUrl=
BrowserCallbackableUrl=
bBindBrowserToUser=False
bShowBrowserPointer=False
MaxNumAudioSources=0
OpusBehavior=Default
MaxConcurrentHardwareDecodes=0
AudioMemoryPoolInitialSizeKB=3072
AudioMemoryPoolIncreaseSizeKB=256
SpatializationPlugin=
SourceDataOverridePlugin=
ReverbPlugin=
OcclusionPlugin=
CompressionOverrides=(bOverrideCompressionTimes=False,DurationThreshold=5.000000,MaxNumRandomBranches=0,SoundCueQualityIndex=0)
CacheSizeKB=0
MaxChunkSizeOverrideKB=0
bForceLegacyStreamChunking=False
ZerothChunkSizeForLegacyStreamChunking=0
bResampleForDevice=False
SoundCueCookQualityIndex=-1

[ConsoleVariables]
MaxSampleRate=0.000000
HighSampleRate=0.000000
MedSampleRate=0.000000
LowSampleRate=0.000000
MinSampleRate=0.000000
CompressionQualityModifier=0.000000
AutoStreamingThreshold=0.000000
GameCardSizeGB=0
GameCardClockRate=0

[Core.StringTable]
+StringTableRedirects=(StringTable="/Game/Data/StringText/ST_UI_Settings_Nebula.ST_UI_Settings_Nebula",OldKey="Game.Vibration",NewKey="Game.Vibration.Nintendo")
+StringTableRedirects=(StringTable="/Game/Data/StringText/ST_UserManagement_Nebula.ST_UserManagement_Nebula",OldKey="Text.ReconnectControllerP1",NewKey="Reconnect.ControllerP1.Switch")
+StringTableRedirects=(StringTable="/Game/Data/StringText/ST_UserManagement_Nebula.ST_UserManagement_Nebula",OldKey="Text.ReconnectControllerP2",NewKey="Reconnect.ControllerP1.Switch")

