[OnlineSubsystem]
DefaultPlatformService=GDK

[OnlineSubsystemGDK]
AchievementMode=2017
;!AutoSubscribePresenceStats=ClearArray
;+AutoSubscribePresenceStats="Achievement.AchievementIndex.8"
;+AutoSubscribePresenceStats="Achievement.AchievementIndex.9"
;+AutoSubscribePresenceStats="Deaths"
;+AutoSubscribePresenceStats="GameProgress"
;+AutoSubscribePresenceStats="HighScore"
;+AutoSubscribePresenceStats="HighScore.MapNameString.Highrise"
;+AutoSubscribePresenceStats="HighScore.MapNameString.Sanctuary"
;+AutoSubscribePresenceStats="Kills"
;+AutoSubscribePresenceStats="MinutesPlayed"
;+AutoSubscribePresenceStats="RoundsCompleted"
;+AutoSubscribePresenceStats="RoundsStarted"
;+AutoSubscribePresenceStats="SessionsCompleted"
;+AutoSubscribePresenceStats="SessionsCompleted.MapNameString.Highrise"
;+AutoSubscribePresenceStats="SessionsCompleted.MapNameString.Sanctuary"
;+AutoSubscribePresenceStats="SessionsCompleted.PlayerWon.0"
;+AutoSubscribePresenceStats="SessionsCompleted.PlayerWon.1"
;+AutoSubscribePresenceStats="SessionsStarted"
;+AutoSubscribePresenceStats="TotalScore"

[UserManager]
;ShooterGame has a welcome screen, so no need to auto-add a user with UI
bSuppressDefaultLiveLoginUI=True

[/Script/WindowsTargetPlatform.WindowsTargetSettings]
ApplicationForegroundColor=Dark
ApplicationBackgroundColor=(B=64,G=0,R=0,A=0)
bEnableAutoResourcePacks=True

PackageVersion=1.0.0.0

;Content ID to update
ContentId=c26ec519-6769-4a66-80c6-d20d3374b586

DefaultDisplayName=PAW Patrol™: Dino World
PackageName=OutrightGames.ProjectWilds
PublisherName=CN=6C7BB0D6-3C3B-4CD4-96D8-7175B2AEACB8
PublisherDisplayName=Outright Games Ltd
StoreId=9N3P3TRJGWV0
;EKBID=6C7BB0D6-3C3B-4CD4-96D8-7175B2AEACB8
TitleId=757b8245
PrimaryServiceConfigId=00000000-0000-0000-0000-0000757b8245
ProductId=50334e39-5433-3052-c04a-475756305100
MSAAppId=400c076e-26b9-4faa-b48b-b47c2349fe4c
ManifestVersion=Version1
bUseSimplifiedUserModel=True

[/Script/PlayFabParty.PlayFabPartyNetDriver]
;NetConnectionClassName="/Script/PlayFabParty.PlayFabPartyNetConnection"

[/Script/Engine.Engine]
!NetDriverDefinitions=ClearArray
+NetDriverDefinitions=(DefName="GameNetDriver",DriverClassName="/Script/PlayFabParty.PlayFabPartyNetDriver",DriverClassNameFallback="/Script/PlayFabParty.PlayFabPartyNetDriver")
+NetDriverDefinitions=(DefName="BeaconNetDriver",DriverClassName="/Script/PlayFabParty.PlayFabPartyNetDriver",DriverClassNameFallback="/Script/PlayFabParty.PlayFabPartyNetDriver")
+NetDriverDefinitions=(DefName="DemoNetDriver",DriverClassName="/Script/Engine.DemoNetDriver",DriverClassNameFallback="/Script/Engine.DemoNetDriver")

[PlayFab]
; Your Hex PlayFab Title ID String Here
;AppId=81D0B
; Time in seconds to wait after a login failure before trying again
;LoginFailureDelaySeconds=15
; Time in seconds to wait after a successful login to refresh xbox login credentials
;LoginRefreshDelaySeconds=7200

[Core.StringTable]
+StringTableRedirects=(StringTable="/Game/Data/StringText/ST_UI_Settings_Nebula.ST_UI_Settings_Nebula",OldKey="Game.Vibration",NewKey="Game.Vibration.Microsoft")

[ConsoleVariables]
GDK.RequestVirtualDeviceLogin=false