[/Script/PS5PlatformEditor.PS5TargetSettings]
; Example chunk configuration - Note: ShooterGame does not actually have localized content.

; These chunk mappings have negative ChunkIds. This is where we define the list of supported languages.
; We make "en-US" the default language for the title, which is the language the PS5 falls back to when
; the specific language the PS5 is configured for is not on the supported language list.
;+ChunkLanguageMapping=(CultureId="en-US",Label="English",ChunkId="-1",IsDefault=true,IsInitial=false)
;+ChunkLanguageMapping=(CultureId="de-DE",Label="German",ChunkId="-1",IsDefault=false,IsInitial=false)
;+ChunkLanguageMapping=(CultureId="fr-FR",Label="French",ChunkId="-1",IsDefault=false,IsInitial=false)

; Chunk language mappings with empty CultureIds represent chunks which are not language specific.
; If these chunks were language specific, we'd assign specific CultureIds to them.
;+ChunkLanguageMapping=(CultureId="",Label="Common",ChunkId=0,IsDefault=false,IsInitial=true)
;+ChunkLanguageMapping=(CultureId="",Label="Sanctuary",ChunkId=1,IsDefault=false,IsInitial=false)
;+ChunkLanguageMapping=(CultureId="",Label="Highrise",ChunkId=2,IsDefault=false,IsInitial=false)

; The pak files are individually mapped to the specific chunks via custom chunk mappings.
; Wildcard * can also be used in the Pattern to automatically map multiple files to a specific chunk.
;+CustomChunkMapping=(Pattern="shootergame/content/paks/pakchunk0-ps5.pak",ChunkId=0,Type=Main)
;+CustomChunkMapping=(Pattern="shootergame/content/paks/pakchunk1-ps5.pak",ChunkId=1,Type=Main)
;+CustomChunkMapping=(Pattern="shootergame/content/paks/pakchunk2-ps5.pak",ChunkId=2,Type=Main)

[SystemSettings]
; UI
UI.SlateSDFText.RasterizationMode=Msdf
UI.SlateSDFText.ResolutionLevel=2
; Reset Async Trace Hitch Threshold for Collision
AsyncTraceDelegateHitchThresholdMS=0.3
; Forced by Unreal to non-scalable values
; https://udn.unrealengine.com/s/question/0D5QP00000BXjs20AD/why-is-fxniagaraqualitylevelmin-and-max-set-to-3-by-default-for-ps5
fx.Niagara.QualityLevel.Min=0
fx.Niagara.QualityLevel.Max=4

[Audio]
AudioDeviceModuleName=
; Defining below allows switching to audio mixer using -audiomixer commandline
AudioMixerModuleName=
PlatformHeadroomDB=0
UseAudioMixer=false

[Voice] 
bEnabled=false

[OnlineSubsystem]
bHasVoiceEnabled=false
DefaultPlatformService=PS5
;NativePlatformService=PS5

[OnlineSubsystemPS5]
bEnabled=true
bHasVoiceEnabled=false
TaskErrorResponseInformationSize=1024

[OnlineSubsystemPS5.OnlineSession]
!SignalingSessions=ClearArray
+SignalingSessions=GameSession
!PlayerSessionLocalizedText=ClearArray
+PlayerSessionLocalizedText="(en-US=Player Session)"
; A set of players that all have NAT type 3 will not be matched together, even if they could 
; connect due to being on the same network.  Uncomment the value below to advertise a
; specific NAT type (only in non-shipping builds)
; MatchmakingNatTypeOverride=2

; [CB]
PlayerSessionName=GameSession
;bGameSessionRequiresPlayerSession=false
; [CB]

[OnlineSubsystemPS5.OnlineGameActivity]
ActivityAvailabilityChangedEventName=Event_ActivityAvailabilityChange
StartActivityEventName=Event_ActivityStart
EndActivityEventName=Event_ActivityEnd
ResumeActivityEventName=Event_ActivityResume
UpdateLocationEventName=Event_LocationChange
ResetAllActiveActivitiesEventName=Event_ActivityTerminate

[OnlineSubsystemPS5.TitleFile]
ServiceLabel=0
+FileSpec=TitleFile0.bin SLOT=0

[OnlineSubsystemPS5.UserCloud]
ServiceLabel=0
+SlotSpecs=UserCloud0.bin SLOT=0

[OnlineSubsystemPS5.Leaderboards]
ServiceLabel=0
;ShooterAllTimeMatchResults.ShooterAllTimeMatchResultsScore=0
;ShooterAllTimeMatchResults.ShooterAllTimeMatchResultsFrags=1
;ShooterAllTimeMatchResults.ShooterAllTimeMatchResultsDeaths=2
;ShooterAllTimeMatchResults.ShooterAllTimeMatchResultsMatchesPlayed=3

[OnlineSubsystemPS5.Achievements]
bEnabled=true
ServiceLabel=0

[OnlineSubsystemPS5.UDS]
bEnabled=true

[Core.StringTable]
+StringTableRedirects=(StringTable="/Game/Data/StringText/ST_UI_Settings_Nebula.ST_UI_Settings_Nebula",OldKey="Game.Vibration",NewKey="Game.Vibration.Sony.PS5")
;+StringTableRedirects=(StringTable="/Game/Data/StringText/ST_UI_Nebula.ST_UI_Nebula",OldKey="WelcomeScreen.PressKey",NewKey="WelcomeScreen.PressKeySony")
+StringTableRedirects=(StringTable="/Game/Data/StringText/ST_UserManagement_Nebula.ST_UserManagement_Nebula",OldKey="Text.ReconnectControllerP1",NewKey="Reconnect.ControllerP1.PS5")
+StringTableRedirects=(StringTable="/Game/Data/StringText/ST_UserManagement_Nebula.ST_UserManagement_Nebula",OldKey="Text.ReconnectControllerP2",NewKey="Reconnect.ControllerP1.PS5")
+StringTableRedirects=(StringTable="/Game/Data/StringText/ST_UserManagement_Nebula.ST_UserManagement_Nebula",OldKey="Text.SaveFailedContinueWithoutSaving",NewKey="Text.SaveFailedContinueWithoutSavingPS5")