[/Script/PS4PlatformEditor.PS4TargetSettings]

TitleID=HP3768-CUSA53618_00-PROJECTWILDS0000

GenerateSFO=false
CopyLatestPatch=false
StorageType=PPST_BD25
AppType=PPAT_Full

;bUse7thCore=true
;bEnableShaderPerfAnalysis=true
;this are bytes aligned to 32kb (1024 * 32 * 160, magic number to match desired size)
DefaultSaveSizeBytes=5242880

[/Script/Engine.Engine]
bSmoothFrameRate=false

[SystemSettings]
UI.SlateSDFText.RasterizationMode=Msdf
UI.SlateSDFText.ResolutionLevel=2
; Reset Async Trace Hitch Threshold for Collision
AsyncTraceDelegateHitchThresholdMS=0.3
; Forced by Unreal to non-scalable values
; https://udn.unrealengine.com/s/question/0D5QP00000BXjs20AD/why-is-fxniagaraqualitylevelmin-and-max-set-to-3-by-default-for-ps5
fx.Niagara.QualityLevel.Min=0
fx.Niagara.QualityLevel.Max=4

[MemReportCommands]
+Cmd=r.PS4.DumpGPUMem

[Audio]
AudioDeviceModuleName=Ngs2
PlatformHeadroomDB=-3

[OnlineSubsystem]
DefaultPlatformService=PS4
PollingIntervalInMs=20
VoiceNotificationDelta=0.3

[OnlineSubsystemPS4]
bEnabled=true
bAchievementsEnabled=true
bAreRoomsEnabled=false
bLeaderboardsEnabled=false

[LeaderboardsPS4]
NpServiceLabel=0

[OnlineSubsystemPS4.UserCloud]
ServiceLabel=0
+SlotSpecs=UserCloud3.bin SLOT=8
+SlotSpecs=UserCloud1.bin SLOT=1
+SlotSpecs=UserCloud0.bin SLOT=5
+SlotSpecs=UserCloud2.bin SLOT=2
+SlotSpecs=UserCloud4.bin SLOT=3
+SlotSpecs=UserCloud5.bin SLOT=4
+SlotSpecs=UserCloud6.bin SLOT=6
+SlotSpecs=UserCloud7.bin SLOT=7
+SlotSpecs=UserCloud8.bin SLOT=9
+SlotSpecs=UserCloud9.bin SLOT=10
+SlotSpecs=UserCloud10.bin SLOT=11
+SlotSpecs=UserCloud11.bin SLOT=12
+SlotSpecs=UserCloud12.bin SLOT=13
+SlotSpecs=UserCloud13.bin SLOT=14
+SlotSpecs=UserCloud14.bin SLOT=15

[OnlineSubsystemPS4.TitleFile]
ServiceLabel=0
+FileSpec=TitleFile1.bin SLOT=1
+FileSpec=TitleFile0.bin SLOT=0

[/Script/Engine.GameEngine]
!NetDriverDefinitions=ClearArray
+NetDriverDefinitions=(DefName="GameNetDriver",DriverClassName="OnlineSubsystemPS4.PS4NetDriver",DriverClassNameFallback="OnlineSubsystemUtils.IpNetDriver")

[OnlineSubsystemPS4.OnlineMessage]
DefaultImagePath=Testing
DefaultMessageText=UE4 Data Message

[PS4Application]
AgeRequirement=3

[DerivedDataBackendGraph]
!SharedDataCachePath=CLEAR_ARRAY
!AltSharedDataCachePath=CLEAR_ARRAY
AltSharedIsReadOnly=true
MinimumDaysToKeepFile=7

[MobileSlateUI]
bTouchFallbackToMouse=false

[DeviceProfileManager]
DeviceProfileSelectionModule=PS4DeviceProfileSelector

[HTTP]
HttpActivityTimeout=15

[Core.StringTable]
+StringTableRedirects=(StringTable="/Game/Data/StringText/ST_UI_Settings_Nebula.ST_UI_Settings_Nebula",OldKey="Game.Vibration",NewKey="Game.Vibration.Sony.PS4")
;+StringTableRedirects=(StringTable="/Game/Data/StringText/ST_UI_Nebula.ST_UI_Nebula",OldKey="WelcomeScreen.PressKey",NewKey="WelcomeScreen.PressKeySony")
+StringTableRedirects=(StringTable="/Game/Data/StringText/ST_UserManagement_Nebula.ST_UserManagement_Nebula",OldKey="Text.ReconnectControllerP1",NewKey="Reconnect.ControllerP1.PS4")
+StringTableRedirects=(StringTable="/Game/Data/StringText/ST_UserManagement_Nebula.ST_UserManagement_Nebula",OldKey="Text.ReconnectControllerP2",NewKey="Reconnect.ControllerP1.PS4")
+StringTableRedirects=(StringTable="/Game/Data/StringText/ST_UserManagement_Nebula.ST_UserManagement_Nebula",OldKey="Text.SaveFailedContinueWithoutSaving",NewKey="Text.SaveFailedContinueWithoutSavingPS4")