;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsList]
GameplayTagList=(Tag="ComponentTag.NeckMesh",DevComment="")
GameplayTagList=(Tag="Customization",DevComment="")
GameplayTagList=(Tag="Customization.ComponentTag",DevComment="")
GameplayTagList=(Tag="Customization.ComponentTag.SkyeHair",DevComment="")
GameplayTagList=(Tag="Customization.ID",DevComment="")
GameplayTagList=(Tag="Customization.ID.Decoration",DevComment="")
GameplayTagList=(Tag="Customization.ID.Decoration.00",DevComment="")
GameplayTagList=(Tag="Customization.ID.Decoration.01",DevComment="")
GameplayTagList=(Tag="Customization.ID.Decoration.02",DevComment="")
GameplayTagList=(Tag="Customization.ID.Decoration.Default",DevComment="")
GameplayTagList=(Tag="Customization.ID.Hat.00",DevComment="")
GameplayTagList=(Tag="Customization.ID.Hat.01",DevComment="")
GameplayTagList=(Tag="Customization.ID.Hat.02",DevComment="")
GameplayTagList=(Tag="Customization.ID.Hat.03",DevComment="")
GameplayTagList=(Tag="Customization.ID.Hat.04",DevComment="")
GameplayTagList=(Tag="Customization.ID.Hat.05",DevComment="")
GameplayTagList=(Tag="Customization.ID.Hat.06",DevComment="")
GameplayTagList=(Tag="Customization.ID.Hat.07",DevComment="")
GameplayTagList=(Tag="Customization.ID.Hat.08",DevComment="")
GameplayTagList=(Tag="Customization.ID.Hat.09",DevComment="")
GameplayTagList=(Tag="Customization.ID.Hat.Default",DevComment="")
GameplayTagList=(Tag="Customization.ID.Livery",DevComment="")
GameplayTagList=(Tag="Customization.ID.Livery.00",DevComment="")
GameplayTagList=(Tag="Customization.ID.Livery.01",DevComment="")
GameplayTagList=(Tag="Customization.ID.Livery.02",DevComment="")
GameplayTagList=(Tag="Customization.ID.Livery.Default",DevComment="")
GameplayTagList=(Tag="SN_BodyGroom",DevComment="")
GameplayTagList=(Tag="SN_Character",DevComment="")
GameplayTagList=(Tag="SN_Glass",DevComment="")
GameplayTagList=(Tag="SN_HeadGroom",DevComment="")
GameplayTagList=(Tag="SN_Vehicle",DevComment="")
GameplayTagList=(Tag="SN_VehicleArm",DevComment="")
GameplayTagList=(Tag="SN_Wheels",DevComment="")

